### PR TITLE
Add forum support

### PR DESCRIPTION
**Pull request by webdev03**
This adds forums support

### CODE REVIEW

**Comment by hello-smile6** [comment]
@webdev03 Why is IRC so hard? My IRC bot won't work!

**Comment by webdev03** [comment]
@hello-smile6 I'm not sure since I haven't used IRC. But can you give feedback instead?

**Review by hello-smile6 — COMMENTED** [review]
Watch out for /t (I'm on IRC if you need to reply, not checking gh much)

**Comment by webdev03** [comment]
what do you mean?

**Review by webdev03 — COMMENTED** [review]
Ready to merge, merging!

**Pull request merged**
